
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: IoT_project
      MYSQL_USER: iot_user
      MYSQL_PASSWORD: iot_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  node-red:
    image: nodered/node-red:latest
    restart: on-failure
    ports:
      - "1880:1880"
    depends_on:
      - mysql
    volumes:
      - node-red-data:/data
    environment:
      - FLOWS=database.json

  python-init:
    build: .
    depends_on:
      - mysql
    volumes:
      - ./scripts:/app/scripts       # Python scripts
      - ./Data:/app/Data             # CSV files
      - ./.env:/app/.env             # environment variables

volumes:
  mysql-data:
  node-red-data:

